services:

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=fastapi_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python app.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./MinioData:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 20s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  postgres_data:
  minio_data:
