services:

  postgre:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${POSTGRE_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${POSTGRE_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  megapi:
    build: .
    command: python app.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/api
    ports:
      - 8000:8000
    depends_on:
      postgre:
        condition: service_healthy
    restart: always
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    runtime: nvidia

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./MinioData:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: always

volumes:
  postgres_data:
  minio_data:

networks:
  default: 
    name: global_network