version: '3.8'

services:

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=fastapi_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python app.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: