name: Test and Deploy on Raspberry Pi 

on: 
    push:
      branches: [ main, addOpenL3Model ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      DATABASE_URL: 'sqlite:///tests/test.db'
      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      MILVUS_URI: ${{ secrets.MILVUS_URI }}
      MILVUS_API_KEY: ${{ secrets.MILVUS_API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Deploy to Aspire Server on main branch push
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_PI_HOST_LIVEBOX_IP }}
        username: ${{ secrets.SSH_ASPIRE_USERNAME }}
        key: ${{ secrets.ASPIRE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PI_PORT }}
        script: |
          cd /home/hatchi/Projets/megapi
          # Use the PAT directly in the HTTPS URL for authentication
          git fetch https://$GH_PAT_ASPIRE:x-oauth-basic@github.com/Hatchi-Kin/megapi.git main
          git reset --hard FETCH_HEAD
          echo "Rebuilding and restarting services..."
          # Clean up
          unset GIT_ASKPASS
          rm git-askpass-helper.sh