name: Test and Deploy on Raspberry Pi 

on: 
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PI_KEY }}" >> ~/.ssh/known_hosts
    - name: Deploy to Raspberry Pi on main branch push
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_PI_HOST }}
        username: ${{ secrets.SSH_PI_USERNAME }}
        key: ${{ secrets.SSH_PI_KEY }}
        port: ${{ secrets.SSH_PI_PORT }}
        script: |
          cd /home/pi/Documents/megapi
          git pull
          if docker ps | grep -q 'megapi-web-1'; then
            docker compose restart
          else
            docker compose up -d
          fi